// Self-hosts the Latin brand fonts (OFL) as same-origin woff2, cutting Google
// Fonts' render-blocking chain. CJK families stay remote — full faces are megabytes.
// USAGE: `pnpm gen:fonts` (needs internet); commit the woff2 + fonts.css outputs.

import { writeFileSync, mkdirSync } from "node:fs";
import { join } from "node:path";
import { fingerprint, isFresh, saveCache } from "./lib/codegenCache";

// A real desktop Chrome UA so the css2 endpoint returns woff2 (older UAs get ttf).
const UA =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36";

// The Latin brand faces, with the exact weights main.css uses. Keep in sync with
// --font-display / --font-sans in src/assets/css/main.css.
const FAMILIES = ["Bebas+Neue:wght@400", "DM+Sans:wght@400;500;700"];

const FONTS_DIR = "public/fonts";
const CSS_OUT = "src/assets/css/fonts.css";

// Font set + UA decide the output — unchanged with fonts.css present means no
// refetch. `--force` re-fetches (e.g. Google refreshed the faces).
const fp = fingerprint(FAMILIES, UA);
if (!process.argv.includes("--force") && isFresh("fonts", fp, [CSS_OUT])) {
  console.log(`[fonts] config unchanged — skipped. Use --force to re-fetch.`);
  process.exit(0);
}

async function fetchText(url: string): Promise<string> {
  const res = await fetch(url, { headers: { "User-Agent": UA } });
  if (!res.ok) throw new Error(`GET ${url} -> ${res.status}`);
  return res.text();
}

async function fetchBytes(url: string): Promise<Buffer> {
  const res = await fetch(url, { headers: { "User-Agent": UA } });
  if (!res.ok) throw new Error(`GET ${url} -> ${res.status}`);
  return Buffer.from(await res.arrayBuffer());
}

mkdirSync(FONTS_DIR, { recursive: true });

const cssUrl = `https://fonts.googleapis.com/css2?${FAMILIES.map((f) => `family=${f}`).join("&")}&display=swap`;
const googleCss = await fetchText(cssUrl);

// Google returns one @font-face per (family, weight, style, range), each with one
// gstatic woff2 url(): download it, name it from those fields, point url() at /fonts/.
const blocks = googleCss.match(/@font-face\s*\{[^}]*\}/g) ?? [];
const counters = new Map<string, number>();
let outCss = "";
let downloaded = 0;

for (const block of blocks) {
  const family = block.match(/font-family:\s*['"]([^'"]+)['"]/)?.[1] ?? "font";
  const weight = block.match(/font-weight:\s*(\d+)/)?.[1] ?? "400";
  const style = block.match(/font-style:\s*(\w+)/)?.[1] ?? "normal";
  const url = block.match(/url\((https:[^)]+\.woff2)\)/)?.[1];
  if (!url) continue; // skip any non-woff2 face

  const slug = family.toLowerCase().replace(/\s+/g, "-");
  const key = `${slug}-${weight}${style === "italic" ? "-italic" : ""}`;
  const n = (counters.get(key) ?? 0) + 1;
  counters.set(key, n);
  const file = `${key}-${n}.woff2`;

  writeFileSync(join(FONTS_DIR, file), await fetchBytes(url));
  downloaded++;
  outCss += block.replace(url, `/fonts/${file}`).trim() + "\n";
}

writeFileSync(
  CSS_OUT,
  `/* Generated by scripts/build-fonts.ts (pnpm gen:fonts). Do not edit by hand. */\n${outCss}`,
);
saveCache("fonts", fp);

console.log(`[fonts] downloaded ${downloaded} woff2 -> ${FONTS_DIR}/, wrote ${CSS_OUT}`);
console.log("[fonts] NEXT (manual wiring):");
console.log(`  1. main.css: add  @import "./fonts.css";  at the top.`);
console.log(`  2. site.ts: remove "Bebas Neue" + "DM Sans" from the global \`fonts\` list`);
console.log(`     (keep them in the --font-display / --font-sans CSS stacks).`);
console.log(`  3. commit ${FONTS_DIR}/*.woff2 and ${CSS_OUT}.`);
